# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
banner:
  charset: UTF-8
  location: classpath:banner.txt
# ----------------------------------------
# LOGGING PROPERTIES
# ----------------------------------------
logging:
  config: classpath:logback-spring.xml
  file: batch.log
  level:
    org:
      quartz: DEBUG
      hibernate:
        SQL: DEBUG
      springframework: INFO
# ----------------------------------------
# SPRING PROPERTIES
# ----------------------------------------
spring:
  aop:
    auto: true
  beaninfo:
    ignore: true
  devtools:
    livereload:
      enabled: false
      port: 35729
    restart:
      enabled: false
      poll-interval: 1000
    quiet-period: 400
  remote:
    debug:
      enabled: false
      local-port: 8000
    restart:
      enabled: false
      secret-header-name: X-AUTH-TOKEN
  profiles: pro
  http:
    encoding:
      charset: UTF-8
      enabled: true
  info:
    build:
      location: classpath:META-INF/build-info.properties
    git:
      location: classpath:git.properties
  main:
    banner-mode: console
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    continue-on-error: false
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?useSSL=false&nullNamePatternMatchesAll=true
    username:
    #password:
    initialSize: 5
    minIdle: 5
    maxActive: 20
    filters: stat,wall,log4j
    pool-prepared-statements: true
    useSSL: false
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    encoding: UTF-8
    enabled: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  data:
    jpa:
      open-in-view: true
      show-sql: true
      generate-ddl: false
      repositories:
        enabled: true
# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
server:
  port: 8082
  ssl:
    enable: false
    key-store:
    key-store-password:
    keyStoretype:
    keyAlias:
    protocol:
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      pattern: common
      prefix: access_log
      suffix: .log
    uri-encoding: UTF-8
# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------
security:
  basic:
    enabled: false
  enable-csrf: true
  headers:
    cache: true
    content-type: true
    frame: true
    xss: true
    require-ssl: true
# ----------------------------------------
# ENDPOINTS (AbstractEndpoint subclasses)
# ----------------------------------------
endpoints:
  auditevents:
    enabled: true
  enabled: true
  actuator:
    enabled: true
    sensitive: false
  docs:
    enabled: true
    curies:
      enabled: false
    sensitive: false
  health:
    time-to-live: 1000
  hypermedia:
    enabled: false
  jolokia:
    enabled: true
    path: /jolokia
    sensitive: true
  loggers:
    enabled: true
  logfile:
    enabled: true
    path: /logfile
    sensitive: true
  metrics:
    filter:
      enabled: true
      gauge-submissions: merged
    　counter-submissions: merged
management:
  security:
    enabled: false
# ----------------------------------------
# DATA PROPERTIES
# ----------------------------------------
flyway:
  enabled: true
  baseline-version: 1.0
  check-location: false
  locations: classpath:db/migration
  url: jdbc:mysql://localhost:3306/quartz
  username:
  sql-migration-prefix: V
  sql-migration-suffix: .sql
liquibase:
  enabled: false

quartz:
  enabled: true
samplejob:
  frequency: 2000
